SUPABASE_URL = "https://cmdneldiaexqzyztcsch.supabase.co"
SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtZG5lbGRpYWV4cXp5enRjc2NoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc3NjEwNDMsImV4cCI6MjA2MzMzNzA0M30.rOTFpXMCp1c-nuyXw0k15S5xUP3eKvR_Exw0k14LkpM"
